In [58]:
"""
Modules
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics
print(statistics.mean([1,2,3,4,5]))
from math import sin, cos
print(sin(17))

3
-0.9613974918795568


In [60]:
"""
Variables
"""
print(type(17))
print(type(False))
print(type("Hello World"))
print(type(-3.33))

<class 'int'>
<class 'bool'>
<class 'str'>
<class 'float'>


In [3]:
"""
Type conversion
"""
str = "17"
i = int(str)
f = float(str)
print(type(str), str)
print(type(i), i)
print(type(f), f)

<class 'str'> 17
<class 'int'> 17
<class 'float'> 17.0


In [68]:
"""
Numeric Operations
"""
x = 3
y = 2
print(x/y)
print(x//y)
print(x%y)
print(x**y)
print(-x)
print(abs(x))

1.5
1
1
9
-3
3


In [7]:
"""
Slicing
"""
word = "Anurag"
print(word[0])
print(word[2:])
print(word[:5])
print(word[-1])
print(word[-2:])

A
urag
Anura
g
ag


In [12]:
"""
String Methods
"""
word = "hello world"
word.upper()
word.title()
"ll" in word
word.capitalize()

'Hello world'

In [16]:
"""
List index and element
[]
"""
mylist = [2,3,4]
for index, element in enumerate(mylist):
    print("{0} {1}".format(index, element))

0 2
1 3
2 4


In [20]:
"""
Tuple Packing and Unpacking : Swap two numbers
()
"""
x = 1
y = 2
var_tuple = x, y
y, x = var_tuple
print("x: ", x)
print("y: ", y)

x:  2
y:  1


In [29]:
"""
Lists are mutable
"""
l = [1,2,3]
lmap = map(lambda x: x*x, l)
print(list(lmap))
type(list(lmap))

[1, 4, 9]


list

In [26]:
"""
Python uses tuples to return multiple values from functions
"""
def doSomething():
    return 1, 2, 3

x = doSomething();
type(x)


tuple

In [51]:
(False and False and True and False and True and True or True or False or True and False) and False

False

In [88]:
"""
Control Statements
"""
#if
value = 0.5
if value > 0:
    print("+")
elif value < 0:
    print("-")
else:
    print("0")

#for
for i in range(0,2):
    print(i**2, end=" ")
print()

#while
i = 0
while(i < 2):
    print(i, end=" ")
    i +=1
print()

#continue
for i in range(1,10):
    if(i % 2 == 0):
        print("Even :", i,  end="; ")
        continue
    print("Odd :", i, end="; ")
print()

#break
n = 10
for i in range(2,n+1):
    for j in range(2, i):
        if i % j == 0:
            break;
    else:
        print(i, end= " ")
print()

#pass
if (0 < 1):
    pass
    print("nothing")
else:
    print("something")

+
0 1 
0 1 
Odd : 1; Even : 2; Odd : 3; Even : 4; Odd : 5; Even : 6; Odd : 7; Even : 8; Odd : 9; 
2 3 5 7 nothing


In [108]:
"""
Python Functions
"""
def function_name(input_arg1, input_arg2):
    print(input_arg1, input_arg2)
    return input_arg1, input_arg2 #return tuple

function_name("A","B")

#global
x = 0
def inc_x2():
    global x
    x = x + 1
 
inc_x2()
print(x)

#default arguments
def func(z, a=1, b=1):
    print(z, a, b)
func(z=2)

A B
1
2 1 1


In [109]:
square = lambda x: x**2
print(square(2))

4


In [136]:
"""
Dictionaries
{}
"""
x={}
dict = {"benign":"gentle",
        "acerbic":"acidic"}
print(dict)
print(dict["benign"])
print("acerbic" in dict)

for key in dict.keys():
    print(key)
for value in dict.values():
    print(value)
for key, value in dict.items():
    print("Key : ", key, ", Value : ", value)
for index, key in enumerate(dict):
    print(index, key)


{'benign': 'gentle', 'acerbic': 'acidic'}
gentle
True
benign
acerbic
gentle
acidic
Key :  benign , Value :  gentle
Key :  acerbic , Value :  acidic
0 benign
1 acerbic


In [133]:
"""
Sorting Dictionaries
"""
customer = [{"name": "John", "age": "33"},
            {"name": "Jade", "age": "24"},
            {"name": "Juan", "age": "38"},]
print(sorted(customer, key = lambda d: d["age"]))
customer.sort(key = lambda d: d["age"], reverse=True)
print(customer)
print(customer[2])
test = [{True:"A"},{False:"B"}]
print(test)


[{'name': 'Jade', 'age': '24'}, {'name': 'John', 'age': '33'}, {'name': 'Juan', 'age': '38'}]
[{'name': 'Juan', 'age': '38'}, {'name': 'John', 'age': '33'}, {'name': 'Jade', 'age': '24'}]
{'name': 'Jade', 'age': '24'}
[{True: 'A'}, {False: 'B'}]


In [132]:
"""
Sets
"""
list_a = [1,2,3,4,5]
list_b = [3,4,7,8,9]

A = set(list_a)
B = set(list_b)
C = set()
print(A)
print(B)
print(C)
print(A.union(B))
print(A.intersection(B))

{1, 2, 3, 4, 5}
{3, 4, 7, 8, 9}
set()
{1, 2, 3, 4, 5, 7, 8, 9}
{3, 4}


In [142]:
num = {'one':1, 'two':3}
num['two']=2
num

{'one': 1, 'two': 2}

In [151]:
"""
Python Object Model
Everything is object
Variables are references to objects
"""
#Integer objects are immutable
#python preallocates integer objects [-5, 256]
x = -5
y = -5
print(id(x))
print(id(y))

x=1024
y=1024
print(x == y)
print(x is y)
print(id(x))
print(id(y))

1876913440
1876913440
True
False
2258395814992
2258395814480


In [164]:
"""
Exceptions

BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
"""
try:
    x = 100 // 0
except ZeroDivisionError:
    print("Divide by Zero Error !")

try:
    a = [1,2,3]
    a[3] = 4
except IndexError:
    print("Index out of bounds !")
else:
    print(a)
finally:
    print(type(a))

age = 16
if (age < 18):
    raise Exception("Age should be greater than 18 years !")
print(age)


Divide by Zero Error !
Index out of bounds !
<class 'list'>


Exception: Age should be greater than 18 years !

In [204]:
"""
File IO
"""
with open('./test.txt','r') as f:
    for index, data in enumerate(f):
        print("Index {} => {}".format(index,data), end = "\n")

with open('./test.txt','a') as f:
    f.write("This is line\n")

f = None
for i in range(10):
    with open ("my_secret_diary.txt", "w") as f:
        if i > 5:
            break

print(f.closed)

with open('./test1.txt','a') as f:
    f.write("This is line\n")

f = open('./test1.txt', 'w') 

Index 0 => This is line 4

Index 1 => This is line 4

Index 2 => This is line 4

Index 3 => This is line 4

Index 4 => This is line

Index 5 => This is line

Index 6 => This is line

Index 7 => This is line

Index 8 => This is line

Index 9 => This is line

Index 10 => This is line

Index 11 => This is line

Index 12 => This is line

Index 13 => This is line

True


In [ ]:
"""
JSON
"""

import json
json.dumps([1,2,3])


In [205]:
"""
Object Oriented Programming
"""

class Customer:
    pass

customer = Customer()

print(customer)
print(type(customer))


<class '__main__.Customer'>


In [224]:
class Customer:
    def __init__(self, firstName, lastName):
        self.firstName = firstName
        self.lastName = lastName

cust1 = Customer("John", "Due")
cust2 = Customer("James","Chen")
print(cust1.firstName, cust1.lastName)
print(cust2.firstName, cust2.lastName)


John Due
James Chen


In [235]:
class Customer:
    def __init__(self, firstName, lastName, skills=[]):
        self.firstName = firstName
        self.lastName = lastName
        self.skills = skills

    def printUser(self):
        print(self.firstName, self.lastName, self.skills)

customer = Customer("John","Sanders",["AWS","Azure","GCP"])
print(user.printUser(), end = ";")


John Sanders ['AWS', 'Azure', 'GCP']
None;

In [248]:
"""
Numpy
"""
#Array as list - memory efficient container
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [249]:
L = range(1000)
%timeit [i**2 for i in L]

a = np.arange(1000)
%timeit a**2


318 µs ± 14.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.68 µs ± 62.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [250]:
#Interactive help:http://docs.scipy.org/
np.array?

In [251]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [252]:
np.con*?

In [253]:
#Creating arrays
#1-D
a = np.array([0,1,2,3])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))

[0 1 2 3]
1
(4,)
4


In [256]:
#2-D
b = np.array([[0,1,2,3],[4,5,6,7]])
print(b)
print(b.ndim)
print(b.shape)
print(len(b))

[[0 1 2 3]
 [4 5 6 7]]
2
(2, 4)
2


In [263]:
#3-D
c = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,0,1],[2,3,4,5]]])
print(c)
print(c.ndim)
print(c.shape)
print(len(c))

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 0 1]
  [2 3 4 5]]]
3
(2, 2, 4)
2


In [264]:
#4-D
d = np.array([[[[0]],[[4]]],[[[8]],[[2]]]])
print(d)
print(d.ndim)
print(d.shape)
print(len(d))

[[[[0]]

  [[4]]]


 [[[8]]

  [[2]]]]
4
(2, 2, 1, 1)
2


In [267]:
a = np.arange(10)
b = np.arange(1,20,3)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13 16 19]


In [273]:
c = np.linspace(0, 1, 6) 
d = np.linspace(0, 1, 5, endpoint=False)
print(c)
print(d)

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


In [282]:
a = np.ones((2,3))
b = np.zeros((2,4))
c = np.eye(4)
d = np.diag(np.array([1,2,3,4,5]))
print(a)
print(b)
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [290]:
a = np.random.rand(4)
print(a)

b = np.random.randn(4)
print(b)

#If we seed with same value we'll get the same random number
#Randomness depends on OS or current system time
np.random.seed(10)
a = np.random.rand(4)
print(a)
b = np.random.rand(4)
print(b)
np.random.seed(10)
a = np.random.rand(4)
print(a)
b = np.random.rand(4)
print(b)

[0.16911084 0.08833981 0.68535982 0.95339335]
[ 0.00429143 -0.17460021  0.43302619  1.20303737]
[0.77132064 0.02075195 0.63364823 0.74880388]
[0.49850701 0.22479665 0.19806286 0.76053071]
[0.77132064 0.02075195 0.63364823 0.74880388]
[0.49850701 0.22479665 0.19806286 0.76053071]


In [310]:
#Datatype
a = np.array([1, 2, 3])
print(a.dtype)
b = np.array([1., 2., 3.])
print(b.dtype)
c = np.array([1,2,3], dtype=float)
print(c.dtype)
#Default data type
d = np.ones((3, 3))
print(d.dtype)
e = np.zeros((2, 2))
print(e.dtype)
f = np.array([1+2j])
print(f.dtype)
g = np.array([True, False])
print(g.dtype)
h = np.array(["A","B"])
print(h.dtype)
i = np.array(["Alex","Bethy"])
print(i.dtype)

int32
float64
float64
float64
float64
complex128
bool
<U1
<U5
